# Generated by Django 4.2.2 on 2026-02-12 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_unit_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visitor_name', models.CharField(max_length=160)),
                ('arrival_at', models.DateTimeField(help_text='Fecha/hora de llegada')),
                ('valid_days', models.PositiveSmallIntegerField(default=1, help_text='Días de validez desde arrival_at')),
                ('one_time_use', models.BooleanField(default=False, help_text='Si es 1 solo uso (entrada+salida una vez)')),
                ('entry_method', models.CharField(choices=[('CAR', 'Auto'), ('TAXI', 'Taxi'), ('MOTORCYCLE', 'Motocicleta'), ('BIKE', 'Bicicleta'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('code', models.CharField(editable=False, max_length=64, unique=True)),
                ('first_in_at', models.DateTimeField(blank=True, null=True)),
                ('first_out_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visit_passes', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_passes', to='core.unit')),
            ],
        ),
        migrations.CreateModel(
            name='VisitScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=10)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('visit_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='visits.visitpass')),
            ],
        ),
    ]
