# Generated by Django 4.2.2 on 2026-02-13 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_unit_owner'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitpass',
            name='residential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit_passes', to='core.residential'),
        ),
    ]
