# Generated by Django 4.2.2 on 2026-02-13 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_unit_owner'),
        ('visits', '0002_visitpass_residential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitpass',
            name='residential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_passes', to='core.residential'),
        ),
    ]
