# Generated by Django 4.2.2 on 2026-02-16 04:55

import billing.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCharge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(help_text='Primer día del mes (ej: 2026-02-01)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('PAID', 'Pagado'), ('VOID', 'Anulado')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_charges', to='core.residential')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_charges', to='core.unit')),
            ],
            options={
                'ordering': ['-period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSubmission',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, default='', help_text='Folio/Referencia de transferencia', max_length=120)),
                ('receipt_image', models.ImageField(max_length=255, upload_to=billing.models.receipt_upload_path)),
                ('status', models.CharField(choices=[('SUBMITTED', 'En revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='SUBMITTED', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.owner')),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.residential')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_payments', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.unit')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.monthlycharge')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.paymentsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField(help_text='Fecha a partir de la cual aplica esta cuota (incluyente)')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='core.residential')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSubmissionApproval',
            fields=[
            ],
            options={
                'verbose_name': 'Aprobación de pago',
                'verbose_name_plural': 'Aprobaciones de pagos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.paymentsubmission',),
        ),
        migrations.AddIndex(
            model_name='paymentsubmission',
            index=models.Index(fields=['residential', 'status', 'submitted_at'], name='billing_pay_residen_585978_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsubmission',
            index=models.Index(fields=['unit', 'submitted_at'], name='billing_pay_unit_id_5f1cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['charge'], name='billing_pay_charge__4b79b0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment'], name='billing_pay_payment_0dc2e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('payment', 'charge')},
        ),
        migrations.AddIndex(
            model_name='monthlycharge',
            index=models.Index(fields=['residential', 'period'], name='billing_mon_residen_d3fa6c_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycharge',
            index=models.Index(fields=['unit', 'period'], name='billing_mon_unit_id_4a1ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycharge',
            index=models.Index(fields=['status'], name='billing_mon_status_d87391_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlycharge',
            unique_together={('unit', 'period')},
        ),
        migrations.AddIndex(
            model_name='feeschedule',
            index=models.Index(fields=['residential', 'effective_from'], name='billing_fee_residen_427b9e_idx'),
        ),
    ]
