# Generated by Django 4.2.2 on 2026-02-15 06:05

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsubmission',
            name='receipt_image',
            field=models.ImageField(max_length=255, upload_to=billing.models.receipt_upload_path),
        ),
    ]
