# Generated by Django 4.2.2 on 2026-02-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_paymentsubmission_receipt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSubmissionApproval',
            fields=[
            ],
            options={
                'verbose_name': 'Aprobación de pago',
                'verbose_name_plural': 'Aprobaciones de pagos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.paymentsubmission',),
        ),
    ]
