# Generated by Django 4.2.2 on 2026-02-16 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('tax_id', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_type', models.CharField(choices=[('HOUSE', 'Casa'), ('APT', 'Departamento')], default='HOUSE', max_length=10)),
                ('reference', models.CharField(help_text='Ej: Casa 4A, Depto 301', max_length=80)),
                ('street', models.CharField(blank=True, default='', max_length=120)),
                ('ext_number', models.CharField(blank=True, default='', max_length=30)),
                ('int_number', models.CharField(blank=True, default='', max_length=30)),
                ('land_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('construction_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, help_text='Dueño actual (1 unidad por dueño)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='core.owner')),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='core.residential')),
            ],
        ),
        migrations.CreateModel(
            name='StaffResidentialProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_admins', to='core.residential')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_residential_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Residential Profile',
                'verbose_name_plural': 'Staff Residential Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='residential',
            index=models.Index(fields=['name'], name='core_reside_name_136a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='residential',
            index=models.Index(fields=['code'], name='core_reside_code_f2bb9f_idx'),
        ),
        migrations.AddField(
            model_name='owner',
            name='residential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='core.residential'),
        ),
        migrations.CreateModel(
            name='UnitBalanceView',
            fields=[
            ],
            options={
                'verbose_name': 'Saldo por unidad',
                'verbose_name_plural': 'Saldos por unidad',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.unit',),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['residential', 'reference'], name='core_unit_residen_49c86f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('residential', 'reference')},
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['residential', 'email'], name='core_owner_residen_f3aaaa_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['residential', 'phone'], name='core_owner_residen_779a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['residential', 'first_name', 'last_name'], name='core_owner_residen_bc25f4_idx'),
        ),
    ]
