# Generated by Django 4.2.2 on 2026-02-10 18:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('tax_id', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Residential / Condominium',
                'verbose_name_plural': 'Residentials / Condominiums',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('LOT', 'Lote'), ('HOUSE', 'Casa'), ('APT', 'Departamento')], default='HOUSE', max_length=10)),
                ('reference', models.CharField(help_text='Ej: Lote 12, Casa 4A, Depto 301', max_length=80)),
                ('street', models.CharField(blank=True, default='', max_length=120)),
                ('ext_number', models.CharField(blank=True, default='', max_length=30)),
                ('int_number', models.CharField(blank=True, default='', max_length=30)),
                ('land_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('construction_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='core.residential')),
            ],
        ),
        migrations.AddIndex(
            model_name='residential',
            index=models.Index(fields=['name'], name='core_reside_name_136a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='residential',
            index=models.Index(fields=['code'], name='core_reside_code_f2bb9f_idx'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='core.owner'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='core.unit'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['email'], name='core_owner_email_f85316_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['phone'], name='core_owner_phone_c01816_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['first_name', 'last_name'], name='core_owner_first_n_413606_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['residential', 'reference'], name='core_unit_residen_49c86f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('residential', 'reference')},
        ),
        migrations.AddIndex(
            model_name='ownership',
            index=models.Index(fields=['unit', 'end_date'], name='core_owners_unit_id_9341d5_idx'),
        ),
        migrations.AddIndex(
            model_name='ownership',
            index=models.Index(fields=['owner', 'end_date'], name='core_owners_owner_i_a8d99f_idx'),
        ),
    ]
