# Generated by Django 4.2.2 on 2026-02-10 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_staffunitprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffunitprofile',
            options={'verbose_name': 'Staff Unit Profile', 'verbose_name_plural': 'Staff Unit Profiles'},
        ),
        migrations.RemoveField(
            model_name='staffunitprofile',
            name='is_unit_admin',
        ),
        migrations.AddField(
            model_name='staffunitprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffunitprofile',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_admin_profiles', to='core.unit'),
        ),
        migrations.AlterField(
            model_name='staffunitprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_unit_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
