# Generated by Django 4.2.2 on 2026-02-10 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_staffunitprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffResidentialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staff Residential Profile',
                'verbose_name_plural': 'Staff Residential Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='staffunitprofile',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='staffunitprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='residential',
            options={},
        ),
        migrations.AddField(
            model_name='owner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Dueño actual', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='core.owner'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='reference',
            field=models.CharField(help_text='Ej: Casa 4A, Depto 301', max_length=80),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('HOUSE', 'Casa'), ('APT', 'Departamento')], default='HOUSE', max_length=10),
        ),
        migrations.DeleteModel(
            name='Ownership',
        ),
        migrations.DeleteModel(
            name='StaffUnitProfile',
        ),
        migrations.AddField(
            model_name='staffresidentialprofile',
            name='residential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_admins', to='core.residential'),
        ),
        migrations.AddField(
            model_name='staffresidentialprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_residential_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
