# Generated by Django 4.2.2 on 2026-02-11 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_owner_uuid_residential_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='owner',
            name='core_owner_email_f85316_idx',
        ),
        migrations.RemoveIndex(
            model_name='owner',
            name='core_owner_phone_c01816_idx',
        ),
        migrations.RemoveIndex(
            model_name='owner',
            name='core_owner_first_n_413606_idx',
        ),
        migrations.AddField(
            model_name='owner',
            name='residential',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='core.residential'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Dueño actual (debe pertenecer al mismo residencial)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='core.owner'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['residential', 'email'], name='core_owner_residen_f3aaaa_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['residential', 'phone'], name='core_owner_residen_779a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['residential', 'first_name', 'last_name'], name='core_owner_residen_bc25f4_idx'),
        ),
    ]
