# Generated by Django 4.2.2 on 2026-02-12 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='owner',
            field=models.OneToOneField(blank=True, help_text='Dueño actual (1 unidad por dueño)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='core.owner'),
        ),
    ]
