# Generated by Django 4.2.2 on 2026-02-13 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_unit_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guards', to='core.residential')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guard_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
